### ISSUE TITLE
[Bug]: LILYGO Lora V2.1-1.6 does not shutdown on 0% battery

### ISSUE THREAD

**Issue by denis1482** [meshtastic/firmware#3963] opened 2024-05-23 10:57 UTC
### Category

Other

### Hardware

T-Lora v2 1.6

### Firmware Version

2.3.6.7a3570a

### Description

LILYGO Lora V2.1-1.6 does not shutdown on 0% battery
How to reproduce: leave it on battery and it will stay on even on 2.90V (3.20V minimum for Li-ion).
Hardware battery protection may be present and may be not, but once firmware is capable of measuring the battery voltage, it should shutdown the hardware on a configured battery level (if shutdown is not supported, super-deep-sleep can be used)

**Comment by todd-herbert** [comment] 2024-05-23 16:29
This *might* have been addressed by https://github.com/meshtastic/firmware/pull/3884.
Do you think you could check if the problem is still there in 2.3.10?

**Closed** 2024-05-23 17:03 UTC
Labels: bug
