### ISSUE TITLE
[Feature Request]: Truncate gps coordinates to a user-selected value

### ISSUE THREAD

**Issue by weirdal3333** [meshtastic/firmware#3206] opened 2024-02-11 05:15 UTC
### Platform

ESP32

### Description

Some people would really like it if their device didn't share their exact coordinates down to the millimeter... There are a lot of crazy people out there after all.

Truncating a location to 5(XX.yyyyy), 4(XX.yyyy), 3, or even 0 (XX.) is an extremely valuable feature for some folks. It would also help deal with the rounding errors that sometimes pop up in the app.

A slider from 8 to 0, or a text box with an increment/decrement button in the app would be great for this!

**Comment by andrekir** [comment] 2024-02-11 08:33
Duplicate of #3092

**Closed by andrekir** 2024-02-11 08:33 UTC
Labels: enhancement
