### ISSUE TITLE
[Bug]: Blue LED is on while in sleep

### ISSUE THREAD

**Issue by rudydevolder** [meshtastic/firmware#2289] opened 2023-02-19 14:21 UTC
### Category

Other

### Hardware

T-Echo

### Firmware Version

2.0.19

### Description

While device is in sleep mode there's a blue LED inside the T-echo that remains on

**Comment by garthvh** [comment] 2023-02-19 14:51
Duplicate of https://github.com/meshtastic/firmware/issues/1493

**Closed by garthvh** 2023-02-19 14:51 UTC
Labels: duplicate, hardware cantfix
