### ISSUE TITLE
[Feature Request]: Expire node after x time of no contact.

### ISSUE THREAD

**Issue by kghunt** [meshtastic/firmware#3253] opened 2024-02-20 09:13 UTC
### Platform

ESP32

### Description

Like a lot of people I am constantly resetting my nodedb to clean up nodes I have not seen for days/ weeks. It would be good if you could configure a timeout where after a node is automatically removed.

**Comment by thebentern** [comment] 2024-02-20 15:29
Duplicate of https://github.com/meshtastic/protobufs/issues/445

**Closed by thebentern** 2024-02-20 15:29 UTC
Labels: duplicate, enhancement
