### ISSUE TITLE
[Bug]: ESP32 goes into error after uploading VS CODE

### ISSUE THREAD

**Issue by gadiscz** [meshtastic/firmware#3961] opened 2024-05-23 09:08 UTC
### Category

Hardware Compatibility

### Hardware

DIY

### Firmware Version

2.3.6.7

### Description

![error](https://github.com/meshtastic/firmware/assets/68325983/d3d332cd-c5ef-4d01-8c0b-e9ac0511d310)
Hi, I'm trying to upload fw pres VS Code to ESP32, but after successfully uploading, I get an ESP32 error and reboot.

It works through the web, I just don't get VS Code.
Other projects work for me in VS Code.
What could be wrong?

**Comment by roha-github** [comment] 2024-05-23 09:44
I don't have problem with ESP32 and that firmware. Tested build and upload via VSCode on old Heltec V2 and newer Heltec V3.

**Comment by gadiscz** [comment] 2024-05-23 09:57
![esp_ver](https://github.com/meshtastic/firmware/assets/68325983/c1f035fd-e887-4138-942b-196519d6cf73)

I downloaded from git fw to the VS Code folder.
I choose "default_envs = meshtastic-diy-v1" or "default_envs = nano-g1-explorer" both have ESP32 and without any change I compile and upload to ESP32. (ESP+OLED+RA-01SH) via the web it works, I just have to change the code because of the RA-01SH)

I tried uploading through esptool and also the same error.

**Comment by todd-herbert** [comment] 2024-05-23 11:53
Just checking: have you seen this page before? https://meshtastic.org/docs/development/firmware/build/
Sorry if I'm repeating info you've already seen. Just want to make sure!

**Comment by roha-github** [comment] 2024-05-23 17:06
If you use DIY, how do you specify the ESP32 variant?

https://github.com/meshtastic/firmware/blob/2f9dc813d3c64b738777bfdba1efc9a4697f7ac2/bin/device-install.bat#L34

**Comment by gadiscz** [comment] 2024-05-23 19:03
Yes, the problem may be that it sets me as a bad ESP32, but I don't know where to set a type? 
And what exactly to set?

**Comment by todd-herbert** [comment] 2024-05-23 23:01
> Yes, the problem may be that it sets me as a bad ESP32, but I don't know where to set a type?
And what exactly to set?

If you follow the [official instructions](https://meshtastic.org/docs/development/firmware/build/), it tells you how to set a type, or how to make a diy type.

**Comment by gadiscz** [comment] 2024-05-24 05:12
yes, I made new hw in Variants and set it in platformio.ini.   but how do i define a board?
![1](https://github.com/meshtastic/firmware/assets/68325983/28c45f02-5927-435d-987f-ea4c74ad9553)
![2](https://github.com/meshtastic/firmware/assets/68325983/fed0965e-cbc2-4097-9bc5-5d49586af932)

**Comment by gadiscz** [comment] 2024-05-24 05:30
Ok, I'll try to make a new board. But on the website it was enough to use DIY v1. I also found out that there is no esp32dev.json file created for ESP32 dev in the boards, so I will try to create it and set the parameters in it.

**Comment by todd-herbert** [comment] 2024-05-24 06:53
>But on the website it was enough to use DIY v1

Oh, I didn't read this part close enough.
If you use "DIY V1" with https://flasher.meshtastic.org, then it works? Is that correct?

Can we try this fresh, from the very start with no changes? First want to check that it's possible to use DIY V1 with meshtastic

Instead of setting default_env, maybe it's easier to select like this:
![select environment](https://github.com/meshtastic/firmware/assets/24772776/3af1f0ae-1ef7-45f9-b160-b8ca7f2f6322)

Then you can click this button to build the firmware and upload it to your device:
![image](https://github.com/meshtastic/firmware/assets/24772776/1bd9199e-2f7e-4dc5-b59d-44c1ced52a4c)

Is this the same technique you have already tried?
I think it's good to test if this technique works first, without any code changes for RA-01SH.

**Comment by gadiscz** [comment] 2024-05-24 11:10
I tried again on the website and the device started up. Then I tried the same bin file with esptool and it also worked.
I then downloaded firmware-master again and selected "meshtastic-diy-v1" again and the same ESP32 error still reboots with the same error. I tried uploading the same generated file "firmware.factory.bin" via esptool and also the same error.

![1](https://github.com/meshtastic/firmware/assets/68325983/9ff1adaa-c80b-486c-860b-e160c8c40fb2)
![2](https://github.com/meshtastic/firmware/assets/68325983/52619969-1c36-4391-95aa-d583da8d88b5)

**Comment by gadiscz** [comment] 2024-05-24 11:16
![image](https://github.com/meshtastic/firmware/assets/68325983/b8c2c6b0-dcac-444a-8d12-01a88fed9b84)

I tried to open another ESP32 project and upload it normally and it works through VS Code.

**Comment by todd-herbert** [comment] 2024-05-24 11:41
Is it okay to see fullscreen screenshots instead? Especially when you are using VS Code, there might be some other clue available there.

I see that when you use the web flasher, you select 2.3.6. I think right now you are probably building the newest version, instead of 2.3.6? Maybe it's good to test if it's possible to build 2.3.6 with VS Code. This might show whether the difference is because of different firmware versions, or whether it's different when you use VS Code.

You can select v2.3.6 in VS Code like this:
![Selecting firmware version in IDE](https://github.com/meshtastic/firmware/assets/24772776/c1f66c45-ba95-4d17-95c2-a91204409a01)

**Comment by todd-herbert** [comment] 2024-05-24 12:34
Interesting! Does 2.3.10 work through VS Code? If yes, then we know the issue is quite new, and maybe know where to look.

**Comment by todd-herbert** [comment] 2024-05-24 12:42
A suggestion just now from @caveman99: can you please try change the VS Code version from 2.3.6 to "master", then use "Erase Flash", and then upload?

![Erase flash](https://github.com/meshtastic/firmware/assets/24772776/4d9976d5-5a48-45a9-8d92-bf922c7bb640)

**Comment by Gnu-Bricoleur** [comment] 2024-05-25 13:31
Hi, 

I was working on adding keypad support for the Chatter https://github.com/meshtastic/firmware/issues/2896
I was building and flashing with VSCode, everything was working properly, I tried to pull the latest master (from a12b992 to 2233507) in order to submit a merge request and now, when flashing the Chatter (it's ESP32 based), it goes into a bootloop.

I reverted all my changes and the current master doesn't works for me on the Chatter
I tried erasing the flash and flashing again

I'm suspecting something happened with this commit https://github.com/meshtastic/firmware/commit/0c9da9aec7ef6b01ab209f22cafb5538cdf58b6e
And I feel it's related to this issue too

**Comment by thebentern** [comment] 2024-05-25 14:10
Yes there is a regression on the original ESP32 that is not present on the S3 based devices which are working fine on the new framework. We will hunt down a resolution before a new release, but as of now, master is not working for these devices.

**Comment by caveman99** [comment] 2024-06-07 14:47
fixed in 2.3.11 firmware release

**Closed by caveman99** 2024-06-07 14:47 UTC
Labels: bug
