### ISSUE TITLE
[Bug]: "heap too low [10000] -> reboot in 5s" does not reboot in given time

### ISSUE THREAD

**Issue by rpsainio** [meshtastic/firmware#2206] opened 2023-01-25 22:13 UTC
### Category

Other

### Hardware

T-Beam, T-Lora v2 1.6

### Firmware Version

2.0.14.cb8532f2-d

### Description

There is a new feature designed to reboot the node when heap gets below 10000 #2165 . Unfortunately this does not work as designed and node did not reboot. Shortening the time it waits before rebooting seems to solve the problem

[reboot_01.txt](https://github.com/meshtastic/firmware/files/10504142/reboot_01.txt)

[reboot_02.txt](https://github.com/meshtastic/firmware/files/10504143/reboot_02.txt)

**Comment by karamo** [comment] 2023-01-25 23:10
Yes, I've also noticed that it's awkwardly placed in **OSThread.cpp**. If this function is called within the 5s, then it comes to a retrigger and delays the reboot.
Why did this work for me?
Probably because I compiled myself with **DEBUG_HEAP** and additionally had the **DEBUG output turned on**.
My suggestion would now be to move this heap test to the **power .cpp**, since it is only called every 30s. Also, both the value 10000 is only estimated by me, since 7000 was too low.
Also, the 5s are just any value and can be reduced arbitrarily.

**Comment by rpsainio** [comment] 2023-01-26 11:50
@karamo I just tested asserting and it seems to work as well, meaning no boot-loops etc. Once low on heap I would not waste time waiting that somebody releases heap rather than rebooting. Will cost some extra messages sent around. According to my test this  happens after ca. 16000 seconds == 4 hours so even an MS-windows survives longer..

**Comment by karamo** [comment] 2023-01-27 13:18
I can confirm it now.
As the last test run on the TLORA 2.1_1.6 board has shown, 10000 heap reserve for reboot is not enough and 5s delay to reboot is too long. It crashed ...
My recommendation:
1) Move the query to Power.cpp
2) set it to 11000
3) set the delay to max. 1s

**Comment by karamo** [comment] 2023-01-27 13:37
Sorry, correction, the **30s** rate at which **[Power] thread** runs can also be too long.
If the **[Blink] thread** runs at 1s, the query would be much better placed here.

**Comment by caveman99** [comment] 2023-01-27 13:48
see #2210

**Comment by caveman99** [comment] 2023-01-30 11:29
fixed in 2.0.14 beta

**Closed by caveman99** 2023-01-30 11:29 UTC
Labels: bug
