### ISSUE TITLE
[Bug]: Heap-Leak at sending via APP

### ISSUE THREAD

**Issue by karamo** [meshtastic/firmware#2258] opened 2023-02-07 11:25 UTC
### Category

Other

### Hardware

T-Beam, T-Lora v2 1.6

### Firmware Version

2.0.18

### Description

Look at the **orange line** = TLORA 2.1_1.6 with FW 2.018 + WiFi & MQTT
From a stable Heap ... sending 2 Messages in the Android APP 2.0.16 ... Heap increases and then decreases continuosly.
![Issue_st-003](https://user-images.githubusercontent.com/3943213/217232006-8d42c8c7-73a4-4a4d-8e0f-e5e7254ac040.png)

Info: magenta & blue are FW 2.0.17
green and ligthgreen are FW 2.0.18
red is FW 2.018 after sending 10 messages via CLI (see #2257)

**Comment by caveman99** [comment] 2023-02-08 00:19
probably duplicate of #2257 - sending a message is the same from CLI as it is from APP

**Comment by karamo** [comment] 2023-02-08 12:01
> probably duplicate of #2257 - sending a message is the same from CLI as it is from APP

No, it's not the same. Here the Heap is falling down ... Heap-Reboot.

**Comment by karamo** [comment] 2023-02-22 19:04
### **Need HELP !!!**
With Android APP 2.0.20 I can't connect to a node via IP with FW 2.0.21.

**Comment by karamo** [comment] 2023-03-16 12:19
With FW 2.1.2 + Patch https://github.com/meshtastic/firmware/pull/2359 Heap ist ok.
No longer Heap-Leak.

Issue can bee closed.

**Closed** 2023-03-16 12:44 UTC
Labels: bug
