### ISSUE TITLE
[Feature Request]: Rangetest change.

### ISSUE THREAD

**Issue by rikianeiros** [meshtastic/firmware#3182] opened 2024-02-08 17:23 UTC
### Platform

ESP32

### Description

I am trying to add a row in the .csv that gives the RSSI on the range test. I have tried it an it is very easy.

**Comment by rikianeiros** [comment] 2024-02-08 17:31
fileToAppend.printf("%d,", mp.rx_rssi); // RX RSSI
    Is just adding this.

**Comment by andrekir** [comment] 2024-02-08 19:52
Duplicate of #2372

**Closed by andrekir** 2024-02-08 19:52 UTC
Labels: enhancement
