### ISSUE TITLE
[Feature Request]: GPS default altitude 0 in stead of 42.950km

### ISSUE THREAD

**Issue by BjornB2** [meshtastic/firmware#3331] opened 2024-03-04 10:41 UTC
### Platform

ESP32

### Description

It seems that when my Heltec with external GPS can't determine the altitude it defaults to 42.950km. It would maybe be better to override the altitude to 0m when this occurs.

**Comment by thebentern** [comment] 2024-03-04 13:11
Never seen this before. Do you have any serial logs to illustrate this occurring?

**Comment by BjornB2** [comment] 2024-03-04 13:18
Not really I'm afraid.
I see there is also a debug log option that I can enable in the device settings. Could I use that to get the required info? If so, where do I find the log after enabling this?

**Comment by BjornB2** [comment] 2024-03-04 13:31
Attached it to my computer and let it run for a minute. See log attached. I changed part of the lat and long for privacy reasons so that is why there are ###'s there.

[mesthastic.log](https://github.com/meshtastic/firmware/files/14482050/mesthastic.log)

If you look at the GPS data you see alt=429xxxxx a couple of times and then it changes to alt=5

I hope this helps. I did have the exact same issue with my T-beam 1.1 btw. I set that one to fixed because of it.

**Comment by Danie10** [comment] 2024-03-06 10:36
I have my Heltec V3 set as fixed location with altitude 14m. Have noticed more than once if I share phone GPS, that when I return home and disable phone GPS share, the fixed location shows the phone's last shared GPS, but has also changed the altitude to 49m. I'd definitely not gone up by 49m so could be that Meshtastic is incorrectly interpreting altitude from phone GPS. Interestingly, the 14m or 15m equates to about 49 feet. Could it be that it is multiplying the phone's GPS altitude in metres to feet? My phone is set to metric, but maybe the raw GPS is in US feet?

**Comment by andrekir** [comment] 2024-03-07 08:43
Duplicate of #3109:

> This is a unsigned/signed problem and does not have anything to do with the specific device. problem is either in TinyGPS++ or in our backend code. The device thinks it's 1400m below sea level.

**Closed by andrekir** 2024-03-07 08:43 UTC
Labels: enhancement
