### ISSUE TITLE
[Bug]: Incorrect battery/charging status on Heltec v2.1 with GPS attached

### ISSUE THREAD

**Issue by ghostop14** [meshtastic/firmware#2004] opened 2022-11-28 20:40 UTC
### Category

Other

### Hardware

Heltec v2.1

### Firmware Version

2.0.6

### Description

With a NEO-6M (GT-U7 module) correctly wired to the heltec board and recognized by Meshtastic, and a battery attached, when on battery OR with power connected the main screen shows the same battery indicator with a "z" in it and reports "powered" on the screen log. The volt-specific screen shows a good voltage (e.g. 4.29V) but then says "0% +U" after it.

**Comment by garthvh** [comment] 2022-11-28 21:39
Duplicate of #769

**Closed by garthvh** 2022-11-28 21:39 UTC
Labels: duplicate, wontfix
