### ISSUE TITLE
[Bug]: Fixed position not persistent

### ISSUE THREAD

**Issue by joneyes** [meshtastic/firmware#3515] opened 2024-03-30 21:03 UTC
### Category

Other

### Hardware

T-Lora v2 1.6, T-Deck

### Firmware Version

2.3.2.63df972 Beta & v2.3.3.8187fa7

### Description

Set device to fixed position in menus. GPS disabled or not present ( i do have a GPS on the T-Deck)
From android App enable "provide phone location to mesh"
Check fixed position fields are populated.
(I have also tried changing a digit in the fields once they are populated, or hand entering data and sending again)
After the reboot, uncheck "provide phone location to mesh" and check position data - all fields have defaulted back to 0.0
Installation was done as a full erase and write.
I have also checked 2.3.3 alpha, and the problem persists there too.
Reverting back to 2.2.4b and when the position is pushed from the phone it persists.
(it would be helpful to be able to populate fixed position data from the web client interface, without having to push it from the app)

**Comment by caveman99** [comment] 2024-03-30 21:10
duplicate of https://github.com/meshtastic/firmware/issues/3514

**Closed by caveman99** 2024-03-30 21:10 UTC
Labels: bug
