### ISSUE TITLE
[Bug]: Nano G1 screen never goes off

### ISSUE THREAD

**Issue by ghostop14** [meshtastic/firmware#2044] opened 2022-12-16 18:10 UTC
### Category

Other

### Hardware

Other

### Firmware Version

2.0.7

### Description

Running Nano g1, t-beam, and heltec v3 next to each other, for some reason even with the screen timeout set to 1m the screen on the Nano never turns off but the others do.

**Comment by garthvh** [comment] 2022-12-17 18:50
This issue exists with all of the SH 1106 based screens

**Comment by garthvh** [comment] 2022-12-17 18:52
Duplicate of https://github.com/meshtastic/firmware/issues/1647

**Closed by garthvh** 2022-12-17 18:52 UTC
Labels: bug
