### ISSUE TITLE
[Bug]:Power Save mode no longer letting screen to wake

### ISSUE THREAD

**Issue by HarukiToreda** [meshtastic/firmware#3512] opened 2024-03-30 06:06 UTC
### Category

Other

### Hardware

Heltec V3

### Firmware Version

2.3.2

### Description

I have a few standalone Heltec V3s with CardKBs that were recently upgraded to firmware 2.3.2. I use them on power save mode. When the screen goes to sleep at 10min I can use the program button to wake it with no issues, but after 15min it no longer wakes the screen when i press the Program button, I can confirm it is still on because the screen wakes up when I send a message to it. It seems something was changed on recent firmwares. I can confirm with another node that has 2.2.22 where it does wake up normally regardless how long the screen is off. 
I've tried to factory reset the node and only turned on Powersave mode and cardkb and it still happens on all nodes with this firmware.

**Comment by garthvh** [comment] 2024-03-30 06:22
The heltec devices may not be the best choice for sleep features

**Comment by 5kamisama5** [comment] 2024-03-30 07:48
> The heltec devices may not be the best choice for sleep features

So you suggest i never upgrade past  firmware 2.2.22? Cause it works just fine there.

**Comment by todd-herbert** [comment] 2024-03-30 10:14
Is the device sleeping (LED heartbeat stopped), or is the screen just off?

**Comment by 5kamisama5** [comment] 2024-03-30 18:16
> Is the device sleeping (LED heartbeat stopped), or is the screen just off?

LED heartbeat is still working, just the screen is off.

**Comment by garthvh** [comment] 2024-03-30 18:34
> > The heltec devices may not be the best choice for sleep features
> 
> So you suggest i never upgrade past firmware 2.2.22? Cause it works just fine there.

A board with battery detection that is finicky is not going to be a great fit for roles that sleep, sleep requires that the power / battery data be reasonably accurate.

**Comment by 5kamisama5** [comment] 2024-03-30 19:28
> battery detection that is finicky is not going to be a great fit for roles that sleep, sleep requires that the power / battery data be reasonably accurate.

it is true it's not the best board but people have it and are using it. A feature that worked before and doesn't work now, means something was changed to break it. I've just taken the time to upgrade to each firmware to pinpoint when it broke. It's not popular among the PROs but people still have this board. 

2.2.22 - Still Works
2.2.23 - Still Works
2.2.24 - Broke Here (Screen not turning on after 15min when button pressed)
2.3.2  - Screen not turning on after 15min
2.3.3  - Screen not turning on after 15min

The device is still has heartbeat, only the screen doesn't turn on when the program button is pressed, screen wakes when I send a message so it is working on power save mode, hope this is enough information to warrant some kind of fix from someone who would take the time to consider it. I am currently starting coding classes so I can be of some use to the community, till then all I can do is point out things I can test with my current ability.

**Comment by garthvh** [comment] 2024-03-30 19:34
Part of why I asked when you were making this recommendation initially is because it should be sleeping like it is now, the behavior you were seeing is not how the is low power works

**Comment by 5kamisama5** [comment] 2024-03-30 19:42
I see, so power save mode should be avoided on the V3. Do you know what  settings are overwritten when this is turned on? like screen time/blutooth shut off, etc. I'd like to manually configure them to get as close as possible if I can't use power save mode on this.

**Comment by garthvh** [comment] 2024-03-30 22:02
I don't really understand still what part of is low power is working for the heltec v3, or how much power it is saving.

**Comment by garthvh** [comment] 2024-03-30 22:02
Probably is not Bluetooth or the screen.

**Comment by 5kamisama5** [comment] 2024-03-31 00:25
**2.2.23 with power save mode on:**
Normal operation: when screen is on it operates at 109mA
Screen turns off after 10min and it operates at 11mA
When I press the program button after 15min it turns the screen on and goes back to 109mA. This is good.

**2.3.2 with power save mode on:**
Normal operation: when screen is on it operates at 109mA
Screen turns off after 10min and it operates at 105mA
After 15min it goes to 11mA, when I press the program button it doesn't turn on the screen on like before and remains on 11mA. No good.

Power save mode saves 10 times power when on light sleep and that's very desirable on standalone devices, but if I have to restart the device anytime i need to turn on the screen it becomes quite tidious.

![20240330_191339](https://github.com/meshtastic/firmware/assets/116696711/f8751f1c-0159-4b8c-8794-fe61684cb13d)
![20240330_184547](https://github.com/meshtastic/firmware/assets/116696711/35136a27-05cb-4cc3-9a10-fd7bd11a5dd9)

**Comment by blueskiesMesh** [comment] 2024-03-31 06:39
Yes, I have many sets of Heltec V3 + Cardkb as standalone devices and they are facing the exact same issue.
Can this be resolved in future firmware?

**Comment by todd-herbert** [comment] 2024-03-31 07:11
I *can* reproduce this bug on Heltec Wireless Paper. 
(Although first requires a hotfix to allow light-sleep, https://github.com/meshtastic/firmware/issues/3517)

Not sure if I personally can help, but I'll take a look at it.

**Comment by brunette-mod** [comment] 2024-04-01 03:33
Is there a solution for this problem? Asking because I have a set of V3's in use as standalone comms for a group of us who use them for hiking and camping. I had been good about updating the firmware on all of them. Having the screen come back to wake mode (when triggered by the program button) is the behavior that people were used to. Also because we put the devices in backpacks etc then look at them periodically to check for messages. TIA

**Comment by todd-herbert** [comment] 2024-04-01 04:16
It should hopefully be fixed with pull request https://github.com/meshtastic/firmware/pull/3521

**Comment by brunette-mod** [comment] 2024-04-01 12:03
@todd-herbert  Thank you so much! Err, need to ask this, but I do have some coding experience, been wondering which subjects I'd need to get up to speed on in order to contribute to the project. Any pointers? Thank you. :)

**Comment by todd-herbert** [comment] 2024-04-01 13:21
@brunette-mod Hey I'm not nearly in-the-loop enough to give you an answer there, but the devs are very active and very helpful over on the [Meshtastic Discord Server](https://discord.com/invite/ktMAKGBnBs).

**Closed** 2024-04-09 00:14 UTC
Labels: bug
