### ISSUE TITLE
[Bug]: Heltec v3 resets after short time or sending

### ISSUE THREAD

**Issue by daniel-hofer** [meshtastic/firmware#2302] opened 2023-02-23 16:40 UTC
### Category

Hardware Compatibility

### Hardware

Other

### Firmware Version

2.0.20.7100416

### Description

New Heltec v3 device was installed via web-flasher and attached to lipo 3000mAh and USB port and 3dBi Antenna.
After starting and configuring the Lora Settings and channels many reboots happened.
After sending message the device reboots and is in a bootloop.
[log.txt](https://github.com/meshtastic/firmware/files/10816035/log.txt)
[info.txt](https://github.com/meshtastic/firmware/files/10816037/info.txt)

**Comment by garthvh** [comment] 2023-02-23 18:27
Duplicate of #2078 same backtrace

**Closed by garthvh** 2023-02-23 18:27 UTC
Labels: bug
