### ISSUE TITLE
[Bug]: Probably bug in calculation of channel utilization

### ISSUE THREAD

**Issue by D4rk4** [meshtastic/firmware#2171] opened 2023-01-18 21:31 UTC
### Category

Other

### Hardware

T-Lora v1

### Firmware Version

2.0.13

### Description
My info: { "myNodeNum": 621102936, "maxChannels": 8, "firmwareVersion": "2.0.13.7e27729-d", "rebootCount": 91, "bitrate": 74.341286, "messageTimeoutMsec": 300000, "minAppVersion": 20300, "hasWifi": true, "channelUtilization": 18.203333, "airUtilTx": 0.048805553 }

Preferences: { "device": { "role": "ROUTER_CLIENT", "serialEnabled": true }, "position": { "positionBroadcastSecs": 120, "positionBroadcastSmartEnabled": true, "fixedPosition": true, "gpsEnabled": true, "gpsUpdateInterval": 120, "gpsAttemptTime": 3600, "positionFlags": 3, "rxGpio": 34, "txGpio": 12 }, "power": { "waitBluetoothSecs": 60, "meshSdsTimeoutSecs": 4294967295, "sdsSecs": 10, "lsSecs": 300, "minWakeSecs": 31104000 }, "network": { "wifiEnabled": true, "wifiSsid": "***", "wifiPsk": "***", "ntpServer": "0.pool.ntp.org" }, "display": { "screenOnSecs": 600 }, "lora": { "usePreset": true, "region": "EU_868", "hopLimit": 5, "txEnabled": true, "txPower": 27, "overrideDutyCycle": true }, "bluetooth": { "fixedPin": 123456 } }

### Relevant log output

```Shell
WARN  | 21:26:48 3077 [DeviceTelemetryModule] Tx air utilization is >0 percent. Skipping this opportunity to send.
```

**Comment by GUVWAF** [comment] 2023-01-19 12:16
The problem is only with the way how it is printed. Should be fixed with #2175.

**Comment by D4rk4** [comment] 2023-01-19 12:25
@GUVWAF may you check, does it's realy a cosmetic issue? I start investigating it because my node stopt tx.

**Comment by GUVWAF** [comment] 2023-01-19 12:30
At his point it will indeed not send this DeviceTelemetry packet, because it exceeded 50% of the duty cycle. Other packets, such as text or position will still be sent.

**Closed** 2023-01-20 15:26 UTC
Labels: bug
