### ISSUE TITLE
[Bug]: T-Beam keeps loosing WiFi connection on 2.0.13.7e27729-d 

### ISSUE THREAD

**Issue by tb0hdan** [meshtastic/firmware#2154] opened 2023-01-16 17:41 UTC
### Category

WiFi

### Hardware

T-Beam

### Firmware Version

2.0.13.7e27729-d

### Description

T-Beam keeps loosing WiFi connection after flashing 2.0.13.7e27729-d instead of 2.0.12

```
[9185594][D][WiFiGeneric.cpp:931] _eventCallback(): Arduino Event: 5 - STA_DISCONNECTED
[9185595][W][WiFiGeneric.cpp:955] _eventCallback(): Reason: 201 - NO_AP_FOUND
[9185598][D][WiFiGeneric.cpp:979] _eventCallback(): WiFi AutoReconnect Running
[9193335][D][WiFiGeneric.cpp:931] _eventCallback(): Arduino Event: 5 - STA_DISCONNECTED
[9193336][W][WiFiGeneric.cpp:955] _eventCallback(): Reason: 4 - ASSOC_EXPIRE
[9193339][D][WiFiGeneric.cpp:979] _eventCallback(): WiFi AutoReconnect Running
```

Can be cured temporarily by reboot

**Comment by tb0hdan** [comment] 2023-01-16 17:49
Related to #2150

**Comment by garthvh** [comment] 2023-01-16 17:54
Duplicate of https://github.com/meshtastic/firmware/issues/1946

**Closed by garthvh** 2023-01-16 17:54 UTC
Labels: bug, duplicate
