### ISSUE TITLE
Messages often come through garbled as "�떗" since recent update

### ISSUE THREAD

**Issue by Obinice** [meshtastic/firmware#3452] opened 2024-03-15 07:58 UTC
Since updating to Android client 2.3.0, messages on LongFast sometimes come through garbled. In one particularly bad case, 8 out of 9 messages received over the course of an hour were garbled. The displayed text is always the same, regardless of the original message content, or the sender.

`�떗`

This was also a few days after applying firmware update 2.2.24 to my Heltec V3, so it is possible the issue resides there, however no iOS users I've spoken with thus far have noted any issues since the firmware update, and in the days between updating the firmware and the Android client this issue did not crop up. So, my first thought is that it could be a client issue (but this needs more investigation).

Attached are three screenshots from the Android app, one showing LongFast with two garbled messages, and the other two screenshots are from the debug screen showing the details of those two messages.

![IMG_20240314_230748](https://github.com/meshtastic/Meshtastic-Android/assets/840511/60f93c38-d0ec-40f5-9dc6-74943379e9b8)
![IMG_20240314_230619](https://github.com/meshtastic/Meshtastic-Android/assets/840511/5e0fd5ff-cb29-41d9-b15d-6b904ab0c0f8)
![IMG_20240314_230642](https://github.com/meshtastic/Meshtastic-Android/assets/840511/c400b287-9d26-40e1-b442-3c2bbd17da6e)

A few other users have discussed the issue in the Meshtastic Discord, they might be able to provide more information, and if there's any more info I can provide just let me know. Thank you for all your hard work, it's greatly appreciated <3

**Comment by geeksville** [comment] 2024-03-21 18:54
This issue has been mentioned on **Meshtastic**. There might be relevant details there:

https://meshtastic.discourse.group/t/2-3-1-traceroute-and-remote-radio-config-broken/11275/4

**Comment by GiuStel** [comment] 2024-03-21 19:28
As an additional element - I don't know if useful - I can tell that most of the nodes here have channel 1, 2 and 3  configured with a PSK.
Channel 0 is MediumFast with standard PSK.
Rolling back (tens of nodes) to version 2.2.24 is taking us back to the normal mesh behaviour.
We're availble for tests if needed. Thanks.

**Comment by grahamrobertslx** [comment] 2024-03-21 19:33
So down graded all my nodes to 2.2.24 and still having the same issue. one node on web and the other on android 2.2.24.
Also...
iOS app to node on web app web app receives the ???? but iOS app says the message had an issue "Implicit ACK from another node". Message sent from web to iOS and the message isn't received.
Messages between iOS and Android work fine.

**Comment by GiuStel** [comment] 2024-03-21 19:40
> So down graded all my nodes to 2.2.24 and still having the same issue. one node on web and the other on android 2.2.24. Also... iOS app to node on web app web app receives the ???? but iOS app says the message had an issue "Implicit ACK from another node". Message sent from web to iOS and the message isn't received. Messages between iOS and Android work fine.
> 
> All with direct trace routes

can you tell that no other nodes with 2.3.x were between yours?

**Comment by grahamrobertslx** [comment] 2024-03-21 19:45
> > So down graded all my nodes to 2.2.24 and still having the same issue. one node on web and the other on android 2.2.24. Also... iOS app to node on web app web app receives the ???? but iOS app says the message had an issue "Implicit ACK from another node". Message sent from web to iOS and the message isn't received. Messages between iOS and Android work fine.
> > All with direct trace routes
> 
> can you tell that no other nodes with 2.3.x were between yours?

They all trace route Direct but can't tell if there was a repeater in-between as i don't believe these are shown in the Trace Route as a hop

**Comment by GUVWAF** [comment] 2024-03-21 19:47
> can you tell that no other nodes with 2.3.x were between yours?

Yes, if there were 2.3.x nodes in between they might not show up in the Traceroute if they have decoding errors.


Just a heads-up: I asked someone that could reproduce it with two nodes (one 2.2.24 and one 2.3.0) to try [this branch](https://github.com/GUVWAF/Meshtastic-device/tree/2_3_0revertHopStart), which is a modified version of 2.3.0 without the suspicious change and that seems to resolve it. So we know that the addition of `hopStart` to the MeshPacket causes this, but we don't know *why*. If we can't resolve it quickly, we'll revert this change to get a new beta out soon.

**Comment by grahamrobertslx** [comment] 2024-03-21 19:51
Ace, if i can be of any more help just let me know. Also happy to test out the modified version of 2.3.0 if you need more experiences 

> > can you tell that no other nodes with 2.3.x were between yours?
> 
> Yes, if there were 2.3.x nodes in between they might not show up in the Traceroute if they have decoding errors.
> 
> Just a heads-up: I asked someone that could reproduce it with two nodes (one 2.2.24 and one 2.3.0) to try [this branch](https://github.com/GUVWAF/Meshtastic-device/tree/2_3_0revertHopStart), which is a modified version of 2.3.0 without the suspicious change and that seems to resolve it. So we know that the addition of `hopStart` to the MeshPacket causes this, but we don't know _why_. If we can't resolve it quickly, we'll revert this change to get a new beta out soon.

Ace, if i can be of any more help just let me know. Also happy to test out the modified version of 2.3.0 if you need more experiences

**Comment by asjmcguire** [comment] 2024-03-21 20:52
> Just a heads-up: I asked someone that could reproduce it with two nodes (one 2.2.24 and one 2.3.0) to try [this branch](https://github.com/GUVWAF/Meshtastic-device/tree/2_3_0revertHopStart), which is a modified version of 2.3.0 without the suspicious change and that seems to resolve it. So we know that the addition of hopStart to the MeshPacket causes this, but we don't know why. If we can't resolve it quickly, we'll revert this change to get a new beta out soon.

I hope we don't have to lose HopStart and HopsAway functionality, but while I was taking a look at the revert - I noticed that via_mqtt has been deleted from NodeDB, is this meant? @GUVWAF

**Comment by GUVWAF** [comment] 2024-03-21 20:54
@asjmcguire Ah, I see. No, that wasn't meant. If we revert it we'll ensure it's done properly, this was just for testing.

**Comment by erayd** [comment] 2024-03-22 06:20
I'm not familiar with this codebase, but the following stood out to me:

> Over LoRa, three previously unused bits in the header are now used for hopStart. Internally when receiving the firmware will parse these bits and put them in a protobuf field hopStart, which is new, but added at the end of the MeshPacket to ensure backwards compatibility.

Looking at `mesh.proto` and `mesh.options`, `MeshPacket.hop_start` is defined as 8 bits, not 3. Is it possible there's an overrun somewhere due to this difference? Where in the source does the conversion between 3 & 8 bits occur?

**Comment by GUVWAF** [comment] 2024-03-22 07:42
@erayd Thanks for thinking along. 
Here it is put into the header: 
https://github.com/meshtastic/firmware/blob/794e99c2f992919e1dea57e3c9cf936ca4648aed/src/mesh/RadioInterface.cpp#L572
Using: 
https://github.com/meshtastic/firmware/blob/794e99c2f992919e1dea57e3c9cf936ca4648aed/src/mesh/RadioInterface.h#L16-L17
And here it is parsed from the header and stored in the struct: 
https://github.com/meshtastic/firmware/blob/794e99c2f992919e1dea57e3c9cf936ca4648aed/src/mesh/RadioLibInterface.cpp#L364

The strange thing is that the decoding errors only happen for the [`payload`](https://github.com/meshtastic/protobufs/blob/master/meshtastic/mesh.proto#L695) inside the [`Data`](https://github.com/meshtastic/protobufs/blob/master/meshtastic/mesh.proto) message in the MeshPacket. This payload itself is again a protobuf message (or just a string for a text message) of a specific type given by the port number, but the length of this `payload` looks somehow incorrect.

**Comment by erayd** [comment] 2024-03-22 08:04
Thanks @GUVWAF - seems it wasn't what I was wondering; that looks sane enough to me 🙂

Will keep looking...

**Comment by asjmcguire** [comment] 2024-03-22 10:15
Potentially what is needed is for a dev to add more verbose logging to 2.2.24 that spits out exactly (raw) what is received over the radio before any processing is done to it. So you can verify that what is received is what should be received. Then some logging to show what is being put out on the radio (again raw).

Then send a message from a 2.3.X node to another 2.3.X node, but with the destination node switched off, ensuring that the 2.2.24 node HAS to rebroadcast.

Then you will at least know if what is arriving at the 2.2.24 node is intact, that way we can at least rule out that 2.3.X is malforming something. That allows us to concentrate on whether it is getting malformed by 2.3.X or whether 2.2.24 is responsible for doing something strange with it, and whether that is during the decoding phase, or whether it is when rebuilding the packet for retransmission.

**Comment by eureekasigns** [comment] 2024-03-22 11:44
> This issue has been mentioned on **Meshtastic**. There might be relevant details there:
> 
> https://meshtastic.discourse.group/t/2-3-1-traceroute-and-remote-radio-config-broken/11275/4

Yes I'll carry on here vs the main forum as this is a very specific and seemingly sporadic issue. 

I did update the app and could trace between the two nodes as well as use admin channel. Otherwise the main one would not do a direct trace when right next to both. 

From a distance, it showed direct. 

Downgraded one node and can trace with app store version of app. 

Of note, the remote admin channel radio config also failed with the non alpha app. 

On hardware, both are RAK boards, 19007. One is older micro USB, the other is C. I have not seen a garbled message but have not tried many. Can connect both nodes to gather console output if needed from a PC but it sounds like what others have found is minimal since the output may need other debug flags enabled to see more raw data?

Only other thing I have going is multiple channels with longfast as a later one in the list. If adding channels is part of the issue, perhaps that is a factor, I do not know. 

If there is something I can do to test further, would be glad to try today. I do not know if I can force it through another hop with 2.2.x or whatever is in the area unless there's some way to force it to use a neighboring node.

**Comment by eureekasigns** [comment] 2024-03-22 15:16
I don't know if this is relevant, but reading the release notes I noticed that the following was updated. 
Could this relate at all to the issue between versions of nodes (and/or potentially app version)?

https://github.com/meshtastic/firmware/pull/3393
https://github.com/meshtastic/firmware/pull/3393/commits/0333eb9e1a968f55e413993fdcbab624c886d96d

Notably the following parts:
platform = platformio/nordicnrf52@^10.4.0

Among changes there, the following is of interest. 
https://github.com/arduino/ArduinoCore-mbed/pull/710
    Add ISGR Root X1 (Let's Encrypt) to CAs
    Add instructions to manage certificates.h and cacert.pem
    
...So, if there is a difference in certificates and/or management of them, could this possibly explain the "garble" that is seen in some cases? 

It is also of interest that in some cases, it is not known whether or not a message is going to the same "channel" (if unknown), correct? In the case of encrypted message, it may be passing through a "last known" node on what it believes should be "primary" ... but landing on a node's 3rd channel, for example. I am still trying to understand that behavior from a post on the discourse board - 

https://meshtastic.discourse.group/t/question-about-private-messages-with-multiple-channels/11092
> "It will use the channel where it most recently heard a Node Info packet from the destination on. That’s most likely the destination’s primary, but can be a secondary."

This may all be unrelated but seemed like a possibility after looking through the above and thought it worth mention.

**Comment by thebentern** [comment] 2024-03-22 16:13
Certificates don't have anything to do with LoRA, and that change happened in 2.3.1. The issue manifests in 2.3.0 as well.

**Comment by asjmcguire** [comment] 2024-03-22 17:04
> The issue manifests in 2.3.0 as well.
And apparently goes away when hopStart is removed from the mesh packet, which is depressing, because Hops Away is the most exciting feature in a long while.

**Comment by thebentern** [comment] 2024-03-22 17:15
> And apparently goes away when hopStart is removed from the mesh packet, which is depressing, because Hops Away is the most exciting feature in a long while.

I agree. This is why we're digging in to see if it's something we can pinpoint with the decoding / encoding and not just yanking the change yet.

**Comment by GUVWAF** [comment] 2024-03-22 19:54
> Potentially what is needed is for a dev to add more verbose logging to 2.2.24 that spits out exactly (raw) what is received over the radio before any processing is done to it.

That's indeed a good idea. Since I still cannot reproduce it (tried other devices as well) I created branches for both [2.2.24](https://github.com/GUVWAF/Meshtastic-device/tree/2_2_24debug) and [2.3.0](https://github.com/GUVWAF/Meshtastic-device/tree/2_3_0_debug) with debug messages containing the raw bytes. Hopefully the artifacts with compiled binaries will be available when the CI finishes [here](https://github.com/GUVWAF/Meshtastic-device/actions/runs/8395717125) for 2.2.24 and [here](https://github.com/GUVWAF/Meshtastic-device/actions/runs/8395622334) for 2.3.0, otherwise you'll also need to compile it yourself if you want to test.

**Comment by GUVWAF** [comment] 2024-03-23 09:31
Good news: I could reproduce and found that the root cause is the NeighborInfo Module. This is because with `hopStart` we can also determine who are neighbors for any other packet. I got full logs from another user and found that the NeighborInfo module was altering the packet even if it wasn’t a NeighborInfo packet. Even when that resulted into decoding errors, it would overwrite the content with garbage. It can only be reproduced if a node with NeighborInfo module enabled on 2.3.0 or 2.3.1 is in between or when testing with two devices on 2.3.0/2.3.1 if **both** have them enabled.

It is fixed by #3474. For now if you use 2.3.0 or 2.3.1, please don’t enable the NeighborInfo module. 

Many thanks to everyone for providing logs or helping in other ways! 
I’m sorry for the inconvenience but happy that we don’t have to revert the `hopStart` addition to the MeshPacket.

**Comment by dantuf** [comment] 2024-03-23 10:44
Very good news indeed! Nice work! I can confirm you fix appears to solve the problem.

**Comment by asjmcguire** [comment] 2024-03-23 11:36
That'll explain why I never saw the problem, I turned NeighbourInfo module off as soon as I updated to the first 2.3.0 alpha, on the basis that any packet with a HopsAway of 0, is clearly a neighbour, thus the NeighbourInfo module is essentially redundant right?

**Comment by GUVWAF** [comment] 2024-03-23 11:46
> on the basis that any packet with a HopsAway of 0, is clearly a neighbour, thus the NeighbourInfo module is essentially redundant right?

Yes and no. Only if all nodes are using >=2.3.0, this can be guaranteed. Furthermore, if you enable the NeighborInfo module also on nodes that you don't connect to with your phone, you receive their NeighborInfo packets, so you know which nodes are *their* neighbors. When collecting these packets e.g. via MQTT, you can draw a graph of how all nodes are connected.

**Closed** 2024-03-23 12:32 UTC
