### ISSUE TITLE
[Bug]: heltec wireless tracker 1.1, no display.

### ISSUE THREAD

**Issue by megabyte2010** [meshtastic/firmware#2905] opened 2023-10-23 00:44 UTC
### Category

Hardware Compatibility

### Hardware

Heltec Wireless Tracker

### Firmware Version

2.2.12 and .13

### Description

I have a heltec wireless tracker v1.1. There is no display. The log shows that this board is being detected as v1.0.

### Relevant log output

��@INFO  | ??:??:?? 2 

//\ E S H T /\ S T / C

INFO  | ??:??:?? 2 Booted, wake cause 0 (boot count 1), reset_reason=reset
DEBUG | ??:??:?? 3 HELTEC Detect Tracker V1.0
DEBUG | ??:??:?? 3 Filesystem files (491520/1048576 Bytes):
DEBUG | ??:??:?? 3  /prefs/channels.proto (53 Bytes)
DEBUG | ??:??:?? 3  /prefs/db.proto (118 Bytes)
DEBUG | ??:??:?? 3  /static/.gitkeep (0 Bytes)
DEBUG | ??:??:?? 3  /static/Logo_Black.svg.gz (592 Bytes)
DEBUG | ??:??:?? 3  /static/Logo_White.svg.gz (600 Bytes)
DEBUG | ??:??:?? 3  /static/apple-touch-icon.png.gz (3162 Bytes)
DEBUG | ??:??:?? 3  /static/favicon.ico.gz (2221 Bytes)
DEBUG | ??:??:?? 3  /static/icon.svg.gz (842 Bytes)
DEBUG | ??:??:?? 3  /static/index-85eb6f51.css.gz (17110 Bytes)
DEBUG | ??:??:?? 3  /static/index-aaac80c4.js.gz (204247 Bytes)
DEBUG | ??:??:?? 3  /static/index-fc2e9253.js.gz (347 Bytes)
DEBUG | ??:??:?? 3  /static/index.html.gz (546 Bytes)
DEBUG | ??:??:?? 3  /static/maplibre-gl-f0d3274b.js.gz (207264 Bytes)
DEBUG | ??:??:?? 3  /static/robots.txt.gz (42 Bytes)
DEBUG | ??:??:?? 3  /static/site.webmanifest.gz (196 Bytes)
DEBUG | ??:??:?? 3 Using analog input 1 for battery level
INFO  | ??:??:?? 3 ADCmod: ADC characterization based on default reference voltage
INFO  | ??:??:?? 3 Scanning for i2c devices...
DEBUG | ??:??:?? 3 Scanning for i2c devices on port 1
INFO  | ??:??:?? 129 No I2C devices found
DEBUG | ??:??:?? 129 acc_info = 0
INFO  | ??:??:?? 129 Meshtastic hwvendor=48, swver=2.2.12.092e6f2
DEBUG | ??:??:?? 129 Setting random seed 1640896851
DEBUG | ??:??:?? 129 Total heap: 274280
DEBUG | ??:??:?? 129 Free heap: 232468
DEBUG | ??:??:?? 129 Total PSRAM: 0
DEBUG | ??:??:?? 129 Free PSRAM: 0
DEBUG | ??:??:?? 129 NVS: UsedEntries 70, FreeEntries 560, AllEntries 630, NameSpaces 3
DEBUG | ??:??:?? 129 Setup Preferences in Flash Storage
DEBUG | ??:??:?? 129 Number of Device Reboots: 2
DEBUG | ??:??:?? 129 OTA firmware version 0.2.1.2fbe7fc
INFO  | ??:??:?? 129 Initializing NodeDB
INFO  | ??:??:?? 129 Loading /prefs/db.proto
INFO  | ??:??:?? 129 Loaded saved devicestate version 22
INFO  | ??:??:?? 129 No /prefs/config.proto preferences found
INFO  | ??:??:?? 129 Installing default LocalConfig
INFO  | ??:??:?? 129 Setting default channel and radio preferences!
DEBUG | ??:??:?? 129 Expanding short PSK #1
INFO  | ??:??:?? 129 Wanted region 0, using UNSET
INFO  | ??:??:?? 129 No /prefs/module.proto preferences found
INFO  | ??:??:?? 129 Installing default ModuleConfig
INFO  | ??:??:?? 129 Loading /prefs/channels.proto
INFO  | ??:??:?? 129 Loaded saved channelFile version 22
INFO  | ??:??:?? 129 No /oem/oem.proto preferences found
DEBUG | ??:??:?? 129 cleanupMeshDB purged 0 entries
DEBUG | ??:??:?? 129 Number of Device Reboots: 2
DEBUG | ??:??:?? 129 Expanding short PSK #1
INFO  | ??:??:?? 129 Wanted region 0, using UNSET
DEBUG | ??:??:?? 129 region=0, NODENUM=0xfa66fb70, dbsize=1
INFO  | ??:??:?? 129 Saving /prefs/db.proto
WARN  | ??:??:?? 129 SPI.begin(SCK=9, MISO=11, MOSI=10, NSS=8)
DEBUG | ??:??:?? 129 Read RTC time as 129
DEBUG | ??:??:?? 129 Setting 37 to output.
INFO  | ??:??:?? 129 Setting GPS power=1
DEBUG | ??:??:?? 129 GPS powerdown using GPS_EN_ACTIVE
DEBUG | ??:??:?? 129 WANT GPS=1
INFO  | ??:??:?? 129 Setting GPS power=1
DEBUG | ??:??:?? 129 GPS powerdown using GPS_EN_ACTIVE
DEBUG | ??:??:?? 129 Using GPIO33 for GPS RX
DEBUG | ??:??:?? 129 Using GPIO34 for GPS TX
DEBUG | ??:??:?? 129 NeighborInfoModule is disabled
INFO  | ??:??:?? 129 External Notification Module Disabled
INFO  | ??:??:?? 129 Doing TFT init
INFO  | ??:??:?? 130 Turning on screen
DEBUG | ??:??:?? 130 Module wants a UI Frame
DEBUG | ??:??:?? 130 Module wants a UI Frame
WARN  | ??:??:?? 130 SX126xInterface(cs=8, irq=14, rst=12, busy=13)
DEBUG | ??:??:?? 130 SX126X_DIO3_TCXO_VOLTAGE defined, using DIO3 as TCXO reference voltage at 1.800000 V
INFO  | ??:??:?? 130 Starting meshradio init...
DEBUG | ??:??:?? 130 (bw=250, sf=11, cr=4/8) packet symLen=8 ms, payloadSize=0, time 231 ms
DEBUG | ??:??:?? 130 (bw=250, sf=11, cr=4/8) packet symLen=8 ms, payloadSize=253, time 3246 ms
INFO  | ??:??:?? 130 Radio freq=906.875, config.lora.frequency_offset=0.000
INFO  | ??:??:?? 130 Set radio: region=UNSET, name=LongFast, config=0, ch=19, power=30
INFO  | ??:??:?? 130 Radio myRegion->freqStart -> myRegion->freqEnd: 902.000000 -> 928.000000 (26.000000 mhz)
INFO  | ??:??:?? 130 Radio myRegion->numChannels: 104 x 250.000kHz
INFO  | ??:??:?? 130 Radio channel_num: 20
INFO  | ??:??:?? 130 Radio frequency: 906.875000
INFO  | ??:??:?? 130 Slot time: 42 msec
INFO  | ??:??:?? 130 Set radio: final power level=22
INFO  | ??:??:?? 130 SX126x init result 0
INFO  | ??:??:?? 130 Frequency set to 906.875000
INFO  | ??:??:?? 130 Bandwidth set to 250.000000
INFO  | ??:??:?? 130 Power output set to 22
DEBUG | ??:??:?? 130 Current limit set to 140.000000
DEBUG | ??:??:?? 130 Current limit set result 0
DEBUG | ??:??:?? 130 Setting DIO2 as RF switch
DEBUG | ??:??:?? 130 SX126X_RXEN not defined, defaulting to RADIOLIB_NC
DEBUG | ??:??:?? 130 SX126X_TXEN not defined, defaulting to RADIOLIB_NC
DEBUG | ??:??:?? 130 Using MCU pin -1 as RXEN and pin -1 as TXEN to control RF switching
INFO  | ??:??:?? 130 Set RX gain to boosted mode; result: 0
INFO  | ??:??:?? 130 SX1262 Radio init succeeded, using SX1262 radio
INFO  | ??:??:?? 130 Not using WIFI
DEBUG | ??:??:?? 130 (bw=250, sf=11, cr=4/8) packet symLen=8 ms, payloadSize=237, time 3057 ms
DEBUG | ??:??:?? 130 LoRA bitrate = 77.526985 bytes / sec
INFO  | ??:??:?? 130 PowerFSM init, USB power=1
DEBUG | ??:??:?? 130 Enter state: BOOT
DEBUG | ??:??:?? 131 [Power] Battery: usbPower=0, isCharging=0, batMv=0, batPct=0
DEBUG | ??:??:?? 131 [Screen] Screen: Started...
INFO  | ??:??:?? 131 [RangeTestModule] Range Test Module - Disabled
INFO  | ??:??:?? 134 [PowerFSM] Initialise the NimBLE bluetooth module
INFO  | ??:??:?? 136 [Screen] Done with boot screen...
DEBUG | ??:??:?? 136 [Screen] showing standard frames
DEBUG | ??:??:?? 136 [Screen] Showing 0 module frames
DEBUG | ??:??:?? 136 [Screen] Total frame count: 103
DEBUG | ??:??:?? 136 [Screen] Added modules.  numframes: 0
DEBUG | ??:??:?? 136 [Screen] Finished building frames. numframes: 2
DEBUG | ??:??:?? 151 [Power] Battery: usbPower=0, isCharging=0, batMv=0, batPct=0
INFO  | ??:??:?? 159 [NodeInfoModule] Sending our nodeinfo to mesh (wantReplies=1)
INFO  | ??:??:?? 159 [NodeInfoModule] sending owner !fa66fb70/Meshtastic fb70/fb70
DEBUG | ??:??:?? 159 [NodeInfoModule] Initial packet id 1831674482, numPacketId 4294967295
DEBUG | ??:??:?? 159 [NodeInfoModule] Update DB node 0xfa66fb70, rx_time=0, channel=0
DEBUG | ??:??:?? 159 [NodeInfoModule] handleReceived(LOCAL) (id=0x6d2d2274 fr=0x70 to=0xff, WantAck=0, HopLim=3 Ch=0x0 Portnum=4 WANTRESP priority=10)
DEBUG | ??:??:?? 159 [NodeInfoModule] No modules interested in portnum=4, src=LOCAL
DEBUG | ??:??:?? 159 [NodeInfoModule] localSend to channel 0
DEBUG | ??:??:?? 159 [NodeInfoModule] Add packet record (id=0x6d2d2274 fr=0x70 to=0xff, WantAck=0, HopLim=3 Ch=0x0 Portnum=4 WANTRESP priority=10)
DEBUG | ??:??:?? 159 [NodeInfoModule] Expanding short PSK #1
DEBUG | ??:??:?? 159 [NodeInfoModule] Using AES128 key!
DEBUG | ??:??:?? 159 [NodeInfoModule] ESP32 crypt fr=fa66fb70, num=6d2d2274, numBytes=50!
WARN  | ??:??:?? 159 [NodeInfoModule] send - lora tx disable because RegionCode_Unset
DEBUG | ??:??:?? 171 [Power] Battery: usbPower=0, isCharging=0, batMv=0, batPct=0
INFO  | ??:??:?? 174 [DeviceTelemetryModule] (Sending): air_util_tx=0.000000, channel_utilization=0.000000, battery_level=0, voltage=0.000000
DEBUG | ??:??:?? 174 [DeviceTelemetryModule] updateTelemetry LOCAL
DEBUG | ??:??:?? 174 [DeviceTelemetryModule] Node status update: 1 online, 1 total
DEBUG | ??:??:?? 174 [DeviceTelemetryModule] showing standard frames
DEBUG | ??:??:?? 174 [DeviceTelemetryModule] Showing 0 module frames
DEBUG | ??:??:?? 174 [DeviceTelemetryModule] Total frame count: 103
DEBUG | ??:??:?? 174 [DeviceTelemetryModule] Added modules.  numframes: 0
DEBUG | ??:??:?? 174 [DeviceTelemetryModule] Finished building frames. numframes: 2
INFO  | ??:??:?? 174 [DeviceTelemetryModule] Sending packet to mesh
DEBUG | ??:??:?? 174 [DeviceTelemetryModule] Update DB node 0xfa66fb70, rx_time=0, channel=0
DEBUG | ??:??:?? 174 [DeviceTelemetryModule] handleReceived(LOCAL) (id=0x6d2d2275 fr=0x70 to=0xff, WantAck=0, HopLim=3 Ch=0x0 Portnum=67 priority=1)
DEBUG | ??:??:?? 174 [DeviceTelemetryModule] No modules interested in portnum=67, src=LOCAL
DEBUG | ??:??:?? 174 [DeviceTelemetryModule] localSend to channel 0
DEBUG | ??:??:?? 174 [DeviceTelemetryModule] Add packet record (id=0x6d2d2275 fr=0x70 to=0xff, WantAck=0, HopLim=3 Ch=0x0 Portnum=67 priority=1)
DEBUG | ??:??:?? 174 [DeviceTelemetryModule] Expanding short PSK #1
DEBUG | ??:??:?? 174 [DeviceTelemetryModule] Using AES128 key!
DEBUG | ??:??:?? 174 [DeviceTelemetryModule] ESP32 crypt fr=fa66fb70, num=6d2d2275, numBytes=11!
WARN  | ??:??:?? 174 [DeviceTelemetryModule] send - lora tx disable because RegionCode_Unset
DEBUG | ??:??:?? 174 [DeviceTelemetryModule] Using channel 0 (hash 0x8)
DEBUG | ??:??:?? 174 [DeviceTelemetryModule] Expanding short PSK #1
DEBUG | ??:??:?? 174 [DeviceTelemetryModule] Using AES128 key!
DEBUG | ??:??:?? 174 [DeviceTelemetryModule] ESP32 crypt fr=fa66fb70, num=6d2d2275, numBytes=11!
DEBUG | ??:??:?? 174 [DeviceTelemetryModule] decoded message (id=0x6d2d2275 fr=0x70 to=0xff, WantAck=0, HopLim=3 Ch=0x0 Portnum=67 priority=1)
DEBUG | ??:??:?? 191 [Power] Battery: usbPower=0, isCharging=0, batMv=0, batPct=0
DEBUG | ??:??:?? 211 [Power] Battery: usbPower=0, isCharging=0, batMv=0, batPct=0
DEBUG | ??:??:?? 231 [Power] Battery: usbPower=0, isCharging=0, batMv=0, batPct=0
```

**Comment by RicInNewMexico** [comment] 2023-10-31 23:24
For the dev that tackles this bug:

https://resource.heltec.cn/download/Wireless_Tracker

There are the schematics for the v1 and v1.1 Heltec Wireless Tracker. Heltec support confirms that there were some pin reassignments that took place with the v1.1 as well as changes to the power supply circuit. Of course they don't specify what the changes were, we'll have to compare schematics.

**Comment by GPSFan** [comment] 2023-11-12 22:12
And an "oh by the way..." the GPS chip used is a Unicore UC6580. there are at least 2 references to UC6850 in GPS.cpp.

**Comment by megabyte2010** [comment] 2023-11-14 02:17
Someone has the factory_test.ino for 1.1? I only find for 1.0

**Comment by megabyte2010** [comment] 2023-12-01 10:45
> @megabyte2010 please measure resistance between I2C's SCL and SDA lines, make sure they aren't shorted

No shorts between pins 41 and 42 and ground. The board was working with the default factory test when i boughted. The log above is saying that the board doesn't have any power source connected, but she was connected thru usb.

**Comment by megabyte2010** [comment] 2023-12-01 18:03
> Is there still no display?

Yes I. Checked between them and ground. No shorts. Like I said, the board was working with the default firmware that came with her. Then I flashed meshtastic and the display stop working. The board seems to freeze for 30 seconds or so, then the white led start flashing. I can connect with the android app but there is no display and maybe no gps.

**Comment by GPSFan** [comment] 2023-12-01 18:11
On the Wireless tracker can you check the voltage on the Ve pin, it is on the bottom left row of pins below the display.
That pin is Vext and needs to be 3.3V as it supplies the GNSS chip and the Display.

**Comment by jp-bennett** [comment] 2023-12-01 18:55
The problem is a mis-detect of the board version. That results in a pin not getting powered, and that pin-off means that the I2C scan works by timing out each probe, rather than getting a nak. The root problem is the mis-detect, but it's not at all clear why some of the 1.1 boards detect properly, and some don't.

**Comment by megabyte2010** [comment] 2023-12-01 19:34
One stupid question... All boards came with factory test installed by default. I have two boards 1.1. All came with that program working. All boards worked the first time I installed meshtastic. One of them, I erased and flashed again. Since then, there is no display. Erasing all eeprom doesn't do nothing. Installing with browser or with cli it's the same. It's "possible" that when we install meshtastic the first time, remains some of the factory code? That's why I want to find the factory_ test for 1.1. To try to reproduce the problem.

**Comment by GPSFan** [comment] 2023-12-01 21:36
So the real questions are, how does the firmware tell a v1.0 from a v1.1 and how/why is it getting confused.

**Comment by megabyte2010** [comment] 2023-12-01 22:09
Anyway, even supplying with 3.3v, the display not always starts. I'm giving up for now.

**Comment by GPSFan** [comment] 2023-12-01 22:16
that could be the interim solution, but now there is only one Wireless Tracker firmware flavor, and only one build variant. Looking at the GPS.cpp, GPS.h files there are lots of ifdefs for v03 and v05, but isn't clear to me (yet) how the decision is made as to v03 or v05.

**Comment by GPSFan** [comment] 2023-12-01 22:20
and maybe this is a problem with your one board. mine flashed ok with .13 and .14, although I could not get the web flasher to work. command line flashing worked three times so far on my board.

**Comment by megabyte2010** [comment] 2023-12-01 22:23
One of them flash and works ok with web flasher, the other only works when she wants. I need the factory file to find out if it is hardware fault or not.

**Comment by jp-bennett** [comment] 2023-12-01 23:23
We've tossed around the idea of saving the results of boot-time probes, to speed up boots. This issue might be best solved with that approach, too.

**Comment by GPSFan** [comment] 2023-12-02 00:35
I'm fairly new to Meshtastic, but not to esp32 nor GPS/GNSS... Mostly u-blox. I'm very interested in the unicore 6580, and the wireless tracker seems to be a good avenue to explore its possibilities. I have several t-beams, a t-deck, a wireless tracker and a Heltec lora v0, or v1. My use case is tracking fast off road vehicles where there is poor line of sight and no internet. I've run several in the field test over the summer (US) with promising results, low operator interaction is important, while situational awareness is key.

**Comment by megabyte2010** [comment] 2023-12-02 10:55
Another thing.. it seems that the integrated gps isn't getting data. I tried a external antenna but with no results. The working board that I have is always saying no sats.

**Comment by thebentern** [comment] 2023-12-02 14:39
> Another thing.. it seems that the integrated gps isn't getting data. I tried a external antenna but with no results. The working board that I have is always saying no sats.

All signs point to the device being a lemon.

**Closed** 2023-12-02 14:40 UTC
Labels: bug

**Comment by GPSFan** [comment] 2023-12-02 15:45
with the original firmware from Heltec, did the GNSS work?

**Comment by caveman99** [comment] 2023-12-03 12:25
that GNSS const may be a typo, but i don't see how changing it oin every plave it occurs wil magically make the chip work.

**Comment by luiscamalmeida** [comment] 2023-12-03 12:47
The typo is not everywhere so there is some code that is not executed. I believe it's the configuration to use GPS + GLONASS.

**Comment by GPSFan** [comment] 2023-12-03 13:59
After finding that typo, I dove a bit deeper into the code and didn't think it would really matter, so I didn't follow it up any more.
I think that this commit:
https://github.com/meshtastic/firmware/commit/2544733ad40769b8dec528309ae7d3c2459f8c2a
might have more of an effect on GNSS operation. and is not in a released version yet.
GPS locking can be a funny thing, only with a good view of the sky and a descent antenna can you do real TTFF analysis.
