### ISSUE TITLE
[Bug]: GPS altitude on T-Beam Supreme says 42949664 meters

### ISSUE THREAD

**Issue by Calimerorulez** [meshtastic/firmware#3398] opened 2024-03-13 17:32 UTC
### Category

Other

### Hardware

T-Beam S3

### Firmware Version

2.3.0

### Description

GPS altitude with a fix of 7 satellites under a clear sky is 42949664 meters according to my display on my T-Beam Supreme :)

**Comment by andrekir** [comment] 2024-03-13 22:21
Duplicate of #3109:

> This is a unsigned/signed problem and does not have anything to do with the specific device. problem is either in TinyGPS++ or in our backend code. The device thinks it's 1400m below sea level.

**Closed by andrekir** 2024-03-13 22:21 UTC
Labels: bug
